### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by Seraphoenixde** [BrilliantTeam/Minecraft-ResourcePack-Migrator#5]
Converting my **bows** and **crossbows** json files results in files that remove the different stages (pulling, rocket, arrow) for the default crossbow and bow.
**Fishing Rods** have the same issue, but also lose their "cast" stages.

Am I doing something wrong here? 

old and converted json files
[assets.zip](https://github.com/user-attachments/files/18169901/assets.zip)
Version 1.21.1 -> 1.21.4

**Comment by RICE0707** [comment]
For bows and crossbows, after conversion, the default texture will be replaced with:  
```json
"model": {
    "type": "range_dispatch",
    "property": "custom_model_data",
    "fallback": {
        "type": "model",
        "model": "item/crossbow" #or "item/bow"
    }
}
```
In theory, there’s no need to make any changes for the vanilla texture to display correctly.  

As for fishing rods, the converter currently does not handle them. However, since you brought it up, I will attempt to add support for fishing rod conversion in the next version.

**Comment by Seraphoenixde** [comment]
Thanks for the quick answer!
The problem is the different stages are not shown at all when you are using the items while using the converted ressourcepack.
If you take a crossbow and reload it, it stays the same texture. Even when it's actually loaded, too.

**Comment by RICE0707** [comment]
It seems this issue does exist. I will try to fix it in the next version.

**Comment by Seraphoenixde** [comment]
Your converter saved me otherwise so much time, do you have paypal or something where I can donate?

**Comment by RICE0707** [comment]
I'm glad I could help save you time updating your resource pack. However, this is a non-profit project. If you can, just give me a star on GitHub—that would mean a lot. Although I have PayPal, I hardly use it due to national policies: [https://www.paypal.com/paypalme/mcbrilliant](https://www.paypal.com/paypalme/mcbrilliant).

**Comment by RICE0707** [comment]
Version 1.3.3 has been released, adding support for the conversion of [fishing rods] and fixing animation errors for vanilla bows and crossbows.
